# Generated by Django 2.2.6 on 2019-11-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserMethodTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.Method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.Symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSeverityUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('user_symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.UserSymptom')),
            ],
        ),
        migrations.CreateModel(
            name='UserMethodTrialStartUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_method_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.UserMethodTrial')),
                ('user_severity_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.UserSeverityUpdate')),
            ],
        ),
        migrations.CreateModel(
            name='UserMethodTrialEndUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_method_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.UserMethodTrial')),
                ('user_severity_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.UserSeverityUpdate')),
            ],
        ),
    ]
