# Generated by Django 2.2.7 on 2019-11-09 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Very Severe')], default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Drawback',
                'verbose_name_plural': 'Drawbacks',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Very Severe')], default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Severity',
                'verbose_name_plural': 'Severities',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.Symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.User')),
            ],
            options={
                'verbose_name': 'User Symptom',
                'verbose_name_plural': 'User Symptoms',
                'unique_together': {('user', 'symptom')},
            },
        ),
        migrations.CreateModel(
            name='UserSymptomUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated at')),
                ('drawback', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wrw.Drawback')),
                ('severity', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wrw.Severity')),
                ('user_symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.UserSymptom')),
            ],
            options={
                'verbose_name': 'User Symptom Update',
                'verbose_name_plural': 'User Symptoms Update',
            },
        ),
        migrations.CreateModel(
            name='UserMethodTrialStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Started at')),
                ('drawback', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wrw.Drawback')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.Method')),
                ('severity', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wrw.Severity')),
                ('user_symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.UserSymptom')),
            ],
            options={
                'verbose_name': 'User Treatment Trial (begin)',
                'verbose_name_plural': 'User Treatment Trials (begin)',
            },
        ),
        migrations.CreateModel(
            name='UserMethodTrialEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ended_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ended at')),
                ('drawback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.Drawback')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrw.Severity')),
                ('user_method_trial_start', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wrw.UserMethodTrialStart')),
            ],
            options={
                'verbose_name': 'User Treatment Trial (end)',
                'verbose_name_plural': 'User Treatment Trials (end)',
            },
        ),
    ]
