# Generated by Django 2.2.7 on 2019-11-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersymptomtrialend',
            options={'verbose_name': 'User Symptom Trial (end)', 'verbose_name_plural': 'User Symptom Trials (end)'},
        ),
        migrations.AlterModelOptions(
            name='usersymptomtrialstart',
            options={'verbose_name': 'User Symptom Trial (start)', 'verbose_name_plural': 'User Symptom Trials (start)'},
        ),
    ]
