# Generated by Django 2.2.7 on 2019-11-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermethodtrialend',
            old_name='ended_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usermethodtrialstart',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usersymptomupdate',
            old_name='updated_at',
            new_name='created_at',
        ),
    ]
