# Generated by Django 2.2.7 on 2019-11-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersymptom',
            name='user_symptom_trial_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrw.UserSymptomTrialEnd'),
        ),
    ]
