# Generated by Django 2.2.7 on 2019-12-03 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermethodtrialend',
            options={'verbose_name': 'User Method Trial End', 'verbose_name_plural': 'User Method Trial Ends'},
        ),
        migrations.AlterModelOptions(
            name='usermethodtrialstart',
            options={'verbose_name': 'User Method Trial Start', 'verbose_name_plural': 'User Method Trial Starts'},
        ),
        migrations.AddField(
            model_name='usersymptom',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
