# Generated by Django 2.2.7 on 2019-12-11 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermethodtrialend',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ended at'),
        ),
        migrations.AlterField(
            model_name='usermethodtrialstart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='usersideeffectupdate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='usersymptom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='usersymptomupdate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
    ]
