# Generated by Django 2.2.7 on 2019-11-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'verbose_name': 'Treatment', 'verbose_name_plural': 'Treatments'},
        ),
        migrations.AlterModelOptions(
            name='usermethodtrial',
            options={'verbose_name': 'User treatment', 'verbose_name_plural': 'User treatments'},
        ),
        migrations.AlterModelOptions(
            name='usermethodtrialendseverity',
            options={'verbose_name': 'Severity (end) of user treatment', 'verbose_name_plural': 'Severities (end) of user treatment'},
        ),
        migrations.AlterModelOptions(
            name='usermethodtrialstartseverity',
            options={'verbose_name': 'Severity (start) of user treatment', 'verbose_name_plural': 'Severities (start) of user treatment'},
        ),
        migrations.AlterModelOptions(
            name='userseverity',
            options={'verbose_name': 'Severity', 'verbose_name_plural': 'Severities'},
        ),
        migrations.AlterUniqueTogether(
            name='usersymptom',
            unique_together={('user', 'symptom')},
        ),
    ]
