# Generated by Django 2.2.7 on 2019-11-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.TextField(),
        ),
    ]
