# Generated by Django 2.2.7 on 2019-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0002_auto_20191106_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userseverityupdate',
            name='description',
            field=models.TextField(),
        ),
    ]
