# Generated by Django 2.2.7 on 2019-11-19 00:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0002_auto_20191114_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersymptom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='usermethodtrialend',
            name='drawback',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wrw.Drawback'),
        ),
        migrations.AlterField(
            model_name='usermethodtrialend',
            name='severity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wrw.Severity'),
        ),
    ]
