# Generated by Django 2.2.7 on 2019-11-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0002_auto_20191108_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermethodtrial',
            unique_together={('user_symptom', 'method')},
        ),
    ]
