# Generated by Django 2.2.7 on 2019-11-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0002_auto_20191123_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersymptom',
            name='user_symptom_trial_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrw.UserSymptomTrialStart'),
        ),
    ]
