# Generated by Django 2.2.7 on 2019-11-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0003_auto_20191106_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseverityupdate',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='userseverityupdate',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
