# Generated by Django 2.2.7 on 2019-11-25 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0003_auto_20191125_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersymptom',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Started at'),
        ),
    ]
