# Generated by Django 2.2.7 on 2019-11-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0003_auto_20191108_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
