# Generated by Django 2.2.7 on 2019-11-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0004_auto_20191108_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
