# Generated by Django 2.2.7 on 2019-11-07 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0004_auto_20191107_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseverityupdate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
