# Generated by Django 2.2.7 on 2019-11-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0005_auto_20191107_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermethodtrialendupdate',
            name='user_method_trial',
        ),
        migrations.AddField(
            model_name='usermethodtrialendupdate',
            name='user_method_trial_start_severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrw.UserMethodTrialStartUpdate'),
        ),
    ]
