# Generated by Django 2.2.7 on 2019-11-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrw', '0005_auto_20191108_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseverity',
            name='severity',
            field=models.PositiveSmallIntegerField(choices=[('0', 'None'), ('1', 'Mild'), ('2', 'Moderate'), ('3', 'Severe'), ('4', 'Very Severe')], default=0),
        ),
    ]
